### ISSUE TITLE
Improve search results page

### ISSUE THREAD

**Issue by bzsinger** [RobertHale/HikingAdventure#141]
- remove headers if no results show (ex. search “Resort” shouldn’t show empty sections for photos and trails)

**Comment by davepcast** [comment]
This change is pretty small, just a conditional rendering of a <p> node. Should take about 1 hour.

**Comment by davepcast** [comment]
This took just less than an hour. We decided to keep the headers but replaced an empty result section with "No results found". Without headers or models being shown, the user might believe the site is unresponsive.
