### ISSUE TITLE
Improve filter interface

### ISSUE THREAD

**Issue by bzsinger** [RobertHale/HikingAdventure#142]
- align filter options visually
 - give guidance to users for what they should enter (not just text boxes) - better validation
 - show chosen filter options in grid page (similar to “Sort by: <attribute>“)
 - fix submit button - make dropdown go away after clicking

**Comment by RobertHale** [comment]
@bzsinger this is what it looks like now when filters are active. Just wanted to check if you think this looks nice.
![capture](https://user-images.githubusercontent.com/14812175/38839265-72ab8c94-419f-11e8-81ab-ec3836ee8c41.JPG)

**Comment by bzsinger** [comment]
Looks great!

**Comment by RobertHale** [comment]
Actual time was around 5 hours of work
