### ISSUE TITLE
Add attributes to the photos model

### ISSUE THREAD

**Issue by bzsinger** [RobertHale/HikingAdventure#143]
- analyze photos for color? content? brightness?
 - (consider using [Google Cloud Vision](https://cloud.google.com/vision)?)

**Comment by RobertHale** [comment]
requires adding new data to api and then updating website to show data. Expect this to take 3-4 hours.

**Comment by RobertHale** [comment]
actual time to completion was 2 hours. Just added new row with contents and lat/lon
