### ISSUE TITLE
Improve sort interface

### ISSUE THREAD

**Issue by bzsinger** [RobertHale/HikingAdventure#145]
- in sort options, make “Sort by: <attribute>” have the same capitalization as it does in the dropdown menu 
 	- ex. “yelprating” -> “Yelp Rating”

**Comment by vponakala** [comment]
Improving interface should take less than an hour.

**Comment by vponakala** [comment]
This took less than an hour as predicted. It was just a simple matter of changing the string that was displayed on the sort by button.
