### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by MTirtowidjojo** [RobertHale/HikingAdventure#153]
Can you guys enable CORS for your API so we can access it on our site to do the visualization?

We do it here for our API:
https://github.com/WeTheSWEople/SWEThePeople/blob/master/backend/app.py#L16

**Comment by RobertHale** [comment]
ya, no problem. we will have it enabled by tomorrow.

**Comment by RobertHale** [comment]
CORS is now enabled on server
